#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT=6379
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/etc/redis/${REDISPORT}.conf"
EXIT_WARNING=1
EXIT_CRITICAL=2
EXIT_OKAY=0

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
                exit $EXIT_WARNING
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    status)
        if [ -f $PIDFILE ]
        then
                PID=$(cat $PIDFILE)

                if [ -x /proc/${PID} ]
                then
                    echo "Redis server is running on $REDISPORT using the config file $CONF with PID $PID"
                    exit $EXIT_OKAY
                else
                    echo "$PIDFILE exists but the Redis process has crashed."
                    exit $EXIT_CRITICAL
                fi
        else
                echo "Redis server is stopped."
                exit $EXIT_WARNING
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
